acaTest/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include("courseRating.urls")),
    path('admin/', admin.site.urls),
]

courseRating/urls.py
from django.urls import path

from . import views


app_name = 'courseRating'
urlpatterns = [
    path("", views.index, name="index"),
    path("register/", views.register, name="register"),
    path("login/", views.user_login, name="login"),
    path("<int:course_id>/", views.detail, name="detail"),
    path("<int:course_id>/rate/", views.rate, name="rate"),
]

courseRating/models.py
from django.db import models
from django.contrib.auth.models import User


class Course(models.Model):
    title = models.CharField(max_length=50)
    description = models.TextField()
    rate = models.FloatField(default=0)
    count = models.IntegerField(default=0)


class Lecture(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    age = models.IntegerField()

courseRating/views.py
from django.shortcuts import render, get_object_or_404
from .models import Course, Lecture
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout



def index(request):
    if request.user.is_authenticated:
        objs = Course.objects.all()
        return render(request, "courseRating/index.html", {'objs':objs})
    else:
        return HttpResponseRedirect('/login')

def register(request):
    if request.method == "GET":
        return render(request, "courseRating/register.html")
    else:
        try:
            first_name = request.POST["firstname"]
            last_name = request.POST["lastname"]
            age = request.POST["age"]
            email = request.POST["email"]
            password = request.POST["password"]
            repeat_password = request.POST["repeat_password"]
        except:
            return render(request, "courseRating/register", {'error_message':"missed field"})

        if password != repeat_password:
            return render(request, "courseRating/register.html", {"error_message": "Password not match."})

        user = User.objects.create_user(username=email, email=email, password=password)
        user.firstName = first_name
        user.lastName = last_name
        user.age = age
        user.save()

        Lecture_user = Lecture(user=user, age=age)
        Lecture_user.save()

        return HttpResponseRedirect("/login")



def user_login(request):
    if request.method == "GET":
        return render(request, 'courseRating/login.html')
    else:
        try:
            username = request.POST["username"]
            password = request.POST["password"]
        except:
            return render(request, 'courseRating/login.html', {'error_message':"missed field"})

    user = authenticate(username=username, password=password)
    if user:
        login(request, user)
        return HttpResponseRedirect('/')
    else:
        render(request, 'courseRating/login', {'error_message':'wrong email or password'})

    return render(request, "courseRating/login.html")


def detail(reqeuest, course_id):
    if reqeuest.user.is_authenticated:
        course = get_object_or_404(Course, pk=course_id)
        return render(reqeuest, 'courseRating/detail.html', {'course':course})
    else:
        return HttpResponseRedirect('/login')

# def rate(request, course_id):
#     global rate_number
#     if request.user.is_authenticated:
#         course = get_object_or_404(Course, pk=course_id)
#         try:
#             rate_number = request.POST["rate"]
#         except:
#             render(request, "courseRating/rate.html", {"error_message":"Enter number for rate!"})
#
#         if rate_number <= 0 or rate_number > 10:
#             render(request, "courseRating/rate.html", {"error_message": "Enter number between 1 and 10!"})
#         course.count+=1
#         course.rate = (course.rate * course.count + rate_number) / (course.count+1)
#         course.save()
#         return HttpResponseRedirect('/')
#     else:
#         return HttpResponseRedirect('/login')


def rate(request, course_id):
    if request.user.is_authenticated:
        course = get_object_or_404(Course, pk=course_id)

        if request.method == "POST":
            try:
                rate_number = int(request.POST.get("rate", 0))
            except ValueError:
                return render(
                    request,
                    "courseRating/rate.html",
                    {"course": course, "error_message": "Enter a valid number for rate!"}
                )

            if rate_number < 1 or rate_number > 10:
                return render(
                    request,
                    "courseRating/rate.html",
                    {"course": course, "error_message": "Enter a number between 1 and 10!"}
                )

            course.rate = (course.rate * course.count + rate_number) / (course.count + 1)
            course.count += 1
            course.save()

            return HttpResponseRedirect('/')
    else:
        return redirect('/login')

    return render(request, "courseRating/rate.html", {"course": course})

courseRating/templates/courseRating/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>detail</title>
</head>
<body>
<h1>{{ course.title }}</h1>
<br>
<br>
<p>{{ course.description }}</p>
<br>
<p>avg rate:{{ course.rate }}</p>
<p>rate count:{{ course.count }}</p>
<br>
<br>
<a href="{% url 'courseRating:rate' course.id %}">RATE</a>
</body>
</html>

courseRating/templates/courseRating/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Courses</title>
</head>
<body>
<ul>
    {% for course in objs %}
        <li><a href="{% url 'courseRating:detail' course.id %}">{{ course.title }}</a></li>
    {% endfor %}
</ul>
</body>
</html>

courseRating/templates/courseRating/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>login</title>
</head>
<body>
    <form action="{% url 'courseRating:login' %}" method="post">
    {% csrf_token %}
        <legend><h1>Login</h1></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        <label for="username">Username</label>
        <input type="text" name="username" id="username" value=""><br>

        <label for="password">Password</label>
        <input type="password" name="password" id="password" value=""><br>

    <input type="submit" value="Login">
    </form>
<br>
<a href="register.html">register</a>
</body>
</html>

courseRating/templates/courseRating/rate.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>rate</title>
</head>
<body>
    <form action="{% url 'courseRating:rate' course.id %}" method="post">
    {% csrf_token %}
        <legend><h1>Rate</h1></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        <label for="rate">rate</label>
        <input type="number" name="rate" id="rate" value=""><br>

    <input type="submit" value="Rate">
    </form>
<br>
</body>
</html>

courseRating/templates/courseRating/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register</title>
</head>
<body>
  <form action="{% url 'courseRating:register' %}" method="post">
  {% csrf_token %}
      <legend><h1>Register</h1></legend>
      {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
      <label for="firstname">first name</label>
      <input type="text" name="firstname" id="firstname" value=""><br>

      <label for="lastname">last name</label>
      <input type="text" name="lastname" id="lastname" value=""><br>

      <label for="age">age</label>
      <input type="number" name="age" id="age" value=""><br>

      <label for="email">email</label>
      <input type="text" name="email" id="email" value=""><br>

      <label for="password">password</label>
      <input type="password" name="password" id="password" value=""><br>

      <label for="repeat_password">repeat password</label>
      <input type="password" name="repeat_password" id="repeat_password" value=""><br>

  <input type="submit" value="Register">
  </form>


<a href="login.html">login</a>
</body>
</html>